spring:
  # 数据源
  datasource:
    url: jdbc:mysql://47.103.130.165:3306/pet-dev?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    # Jasypt加密 可到common-utils中找到JasyptUtil加解密工具类生成加密结果 格式为ENC(加密结果)
    #password: ENC(w4M/AsoI2pPRXftUfYqV4A==)
    password: 192939Aa
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 10
    maxActive: 80
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 10
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: select count(*) from systables
    #logSlowSql: true

