spring:
  profiles:
    active: dev

# Swagger界面内容配置
swagger:
  title: pet API接口文档
  description: pet Api Documentation
  version: 1.0.0

# Mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml